[env]
platform = espressif32
board = esp32dev
framework = arduino


lib_deps =
    milesburton/DallasTemperature@4.0.5
    paulstoffregen/OneWire@^2.3.8 ; Toujours inclure OneWire, car Dallas en dépend
    br3ttb/PID @ ^1.2.1
    
[env:debug]
build_flags = ${env.build_flags} -DDEBUG -Og

[env:release]
build_flags = ${env.build_flags} -Os