[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    bodmer/TFT_eSPI
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1
  -D TFT_MISO=19
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=21        ; <-- On utilise le 21 car le 2 est souvent lié à la LED
  -D TFT_RST=4
  -D SPI_FREQUENCY=10000000 ; On reste prudent à 10MHz
  -D LOAD_GLCD=1  ; Police standard
  -D LOAD_FONT2=1 ; Police moyenne
  -D LOAD_FONT4=1 ; Grosse police
  -D LOAD_FONT6=1 ; Très grosse police (chiffres)